DROP DATABASE IF EXISTS League;
CREATE DATABASE League;
USE League;
CREATE TABLE Player(Identifier_P INTEGER PRIMARY KEY NOT NULL, Username TEXT NOT NULL, Password VARCHAR(50) NOT NULL, CHECK (Password REGEXP '[0-9]' AND Password REGEXP '[A-Za-z]'));
CREATE TABLE Game(Identifier_G INTEGER PRIMARY KEY NOT NULL, Date_Time DATETIME NOT NULL, Duration INTEGER NOT NULL, Winner TEXT NOT NULL);
CREATE TABLE Game_Record(Player INTEGER NOT NULL, Game INTEGER NOT NULL, FOREIGN KEY (Player) REFERENCES Player (Identifier_P), FOREIGN KEY (Game) REFERENCES Game (Identifier_G), Score INTEGER NOT NULL);

INSERT INTO Player VALUES(1,'Eduardo','edu2007');
INSERT INTO Player VALUES(2,'Rafa','725rfaa');
INSERT INTO Player VALUES(3,'Juan','13jA');
INSERT INTO Player VALUES(4,'Victoria', 'VI42');
INSERT INTO Player VALUES(5,'Florencia','Flo555');

INSERT INTO Game VALUES(1,'2024-09-24 10:07:33',22,'Rafa');
INSERT INTO Game VALUES(2,'2024-08-08 18:32:55',13,'Victoria');
INSERT INTO Game VALUES(3,'2024-03-28 07:19:02',25,'Rafa');
INSERT INTO Game VALUES(4,'2023-11-12 02:06:10',7,'Eduardo');
INSERT INTO Game VALUES(5,'2024-05-05 11:19:03',15,'Florencia');

INSERT INTO Game_Record VALUES(1,1,5);
INSERT INTO Game_Record VALUES(2,2,7);
INSERT INTO Game_Record VALUES(2,3,1);
INSERT INTO Game_Record VALUES(5,2,3);
INSERT INTO Game_Record VALUES(4,1,6);
INSERT INTO Game_Record VALUES(3,3,3);

